apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kvstore-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kvstore-deploy
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
